SHELL=/bin/bash
OUT_GRAFANA=out/grafana
OUT_PROMETHEUS=out/prometheus
DASH_TARGETS=$(patsubst %.jsonnet, $(OUT_GRAFANA)/%.json, $(wildcard dash*.jsonnet))
ALERT_TARGETS=$(patsubst %.jsonnet, $(OUT_PROMETHEUS)/%.rules.yaml, $(wildcard alert*.jsonnet))

ALL_JSONNET=$(wildcard *.jsonnet)

PHONY_GOLDEN=$(patsubst %.jsonnet,golden/%.json,$(ALL_JSONNET))
PHONY_DIFF=$(patsubst %.jsonnet,%.diff,$(ALL_JSONNET))

all: $(DASH_TARGETS) $(ALERT_TARGETS)

test: test-fmt golden-diff

test-fmt:
	jsonnet fmt --test $(ALL_JSONNET)

fix-fmt:
	for i in $(ALL_JSONNET); do jsonnet fmt -i $$i;done

clean:
	rm -f $(DASH_TARGETS) $(ALERT_TARGETS)

$(OUT_PROMETHEUS)/%.rules.yaml: $(OUT_PROMETHEUS)/%.json
	@mkdir -p out/prometheus
	python -c 'import sys, yaml, json; yaml.safe_dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)' < $(^) > $(@)

$(OUT_PROMETHEUS)/%.json $(OUT_GRAFANA)/%.json: %.jsonnet
	@mkdir -p out/grafana out/prometheus
	jsonnet $(^) > $(@).tmp && mv $(@).tmp $(@) || rm -f $(@).tmp

golden-diff: $(PHONY_DIFF)

%.diff: %.jsonnet
	diff -u golden/$(*).json <(jsonnet $(<))

golden/%.json: %.jsonnet
	jsonnet $(<) > $(@)

gen-golden: $(PHONY_GOLDEN)

.PRECIOUS: %.jsonnet golden/%.json gen-golden
